"""token_cascade_delete

Revision ID: 02de03983ebe
Revises: 35839f442ce2
Create Date: 2022-12-23 00:36:40.867153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02de03983ebe'
down_revision = '35839f442ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
