"""add_fields_to_kitchen_ing

Revision ID: 070ecb1b96b1
Revises: 02de03983ebe
Create Date: 2022-12-23 01:00:09.585970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070ecb1b96b1'
down_revision = '02de03983ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitchen_ingredient', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('kitchen_ingredient', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('kitchen_ingredient', sa.Column('count', sa.Integer(), nullable=True))
    op.alter_column('kitchen_ingredient', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('kitchen_ingredient_ingredient_id_fkey', 'kitchen_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'kitchen_ingredient', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kitchen_ingredient', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kitchen_ingredient', type_='foreignkey')
    op.drop_constraint(None, 'kitchen_ingredient', type_='foreignkey')
    op.create_foreign_key('kitchen_ingredient_ingredient_id_fkey', 'kitchen_ingredient', 'ingredient', ['ingredient_id'], ['id'])
    op.alter_column('kitchen_ingredient', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('kitchen_ingredient', 'count')
    op.drop_column('kitchen_ingredient', 'weight')
    op.drop_column('kitchen_ingredient', 'user_id')
    # ### end Alembic commands ###
