"""add_recipe_ingredient_table

Revision ID: 166f9c4b00db
Revises: e2fa2d8f9561
Create Date: 2023-01-07 01:22:03.419149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "166f9c4b00db"
down_revision = "e2fa2d8f9561"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_ingredient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("count", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingredient_id"], ["ingredient.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_check_constraint(
        "ck_recipe_ingredient_weight_positive", "recipe_ingredient", "weight > 0"
    )
    op.create_check_constraint(
        "ck_recipe_ingredient_count_positive", "recipe_ingredient", "count > 0"
    )
    op.drop_table("recipes_ingredients")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes_ingredients",
        sa.Column("recipe_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ingredient_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
            name="recipes_ingredients_ingredient_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipe.id"], name="recipes_ingredients_recipe_id_fkey"
        ),
    )
    op.drop_table("recipe_ingredient")
    # ### end Alembic commands ###
