"""nullable_fields_fix

Revision ID: 25ccdb2c33f8
Revises: f7c0fd8cfa55
Create Date: 2023-01-21 04:57:07.755366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ccdb2c33f8'
down_revision = 'f7c0fd8cfa55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'title',
               existing_type=sa.VARCHAR(length=31),
               nullable=False)
    op.alter_column('recipe', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('recipe', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('recipe', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.alter_column('user', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.alter_column('recipe', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('recipe', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('recipe', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ingredient', 'title',
               existing_type=sa.VARCHAR(length=31),
               nullable=True)
    # ### end Alembic commands ###
