"""user_token_tables

Revision ID: 35839f442ce2
Revises: 
Create Date: 2022-12-22 23:43:53.917449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35839f442ce2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=31), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=63), nullable=True),
    sa.Column('password', sa.String(length=63), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('kitchen_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=63), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('kitchen_ingredient')
    op.drop_table('user')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
