"""not_null_fields_in_recipe

Revision ID: 4cdfc7116b84
Revises: 74db72f96b59
Create Date: 2023-01-07 02:20:38.590333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdfc7116b84'
down_revision = '74db72f96b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('step', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('step', 'order',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('step', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('step', 'order',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('step', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('recipe', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
