"""empty message

Revision ID: 664ac39141c1
Revises: ba3feab1f3bd
Create Date: 2022-12-22 04:05:17.497707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664ac39141c1'
down_revision = 'ba3feab1f3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=63), nullable=True))
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
