"""constraint_kitchen_ing

Revision ID: 701b07e6207f
Revises: 070ecb1b96b1
Create Date: 2022-12-23 02:09:38.198957

"""
from alembic import op
from sqlalchemy import func, column


# revision identifiers, used by Alembic.
revision = "701b07e6207f"
down_revision = "070ecb1b96b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_1", "kitchen_ingredient", ["user_id", "ingredient_id"]
    )
    op.create_check_constraint(
        "ck_kitchen_ingredient_weight_positive", "kitchen_ingredient", "weight > 0"
    )
    op.create_check_constraint(
        "ck_kitchen_ingredient_count_positive", "kitchen_ingredient", "count > 0"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_1", "kitchen_ingredient", type_="unique")
    op.drop_constraint("ck_kitchen_ingredient_count_positive", "kitchen_ingredient", type_="check")
    op.drop_constraint("ck_kitchen_ingredient_weight_positive", "kitchen_ingredient", type_="check")
    # ### end Alembic commands ###
