"""create_ingredients_tables

Revision ID: 72c0f3f9b174
Revises: d2b950103ac9
Create Date: 2022-12-15 04:01:37.366743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c0f3f9b174'
down_revision = 'd2b950103ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=31), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitchen_ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
