"""make_title_recipe_unique

Revision ID: 74db72f96b59
Revises: 166f9c4b00db
Create Date: 2023-01-07 01:32:21.868768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74db72f96b59'
down_revision = '166f9c4b00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipe', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    # ### end Alembic commands ###
