"""make_ingredient_title_unique

Revision ID: 8d76e6dfdc1c
Revises: 72c0f3f9b174
Create Date: 2022-12-15 04:10:04.384328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d76e6dfdc1c'
down_revision = '72c0f3f9b174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ingredient', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='unique')
    # ### end Alembic commands ###
