"""add_fields_to_recipe

Revision ID: 9eebc2cacf16
Revises: 2a7f532916a1
Create Date: 2023-01-04 03:24:15.701136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eebc2cacf16'
down_revision = '2a7f532916a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('public', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('recipe', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'author_id')
    op.drop_column('recipe', 'public')
    # ### end Alembic commands ###
