"""add_title_to_recipe

Revision ID: e2fa2d8f9561
Revises: 9eebc2cacf16
Create Date: 2023-01-07 00:56:39.156870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fa2d8f9561'
down_revision = '9eebc2cacf16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('title', sa.String(length=255)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'title')
    # ### end Alembic commands ###
