"""user_password_not_null

Revision ID: f7c0fd8cfa55
Revises: 4cdfc7116b84
Create Date: 2023-01-07 02:21:45.735585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c0fd8cfa55'
down_revision = '4cdfc7116b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    # ### end Alembic commands ###
